"""ajout du rôle

Revision ID: 2501f7fab0f2
Revises: 
Create Date: 2026-06-28 18:20:48.356279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2501f7fab0f2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=50), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('mdp_hash', sa.Text(), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.Column('maj_le', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='blog'
    )
    op.create_table('articles',
    sa.Column('titre', sa.String(length=100), nullable=False),
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('publie', sa.Boolean(), nullable=True),
    sa.Column('auteur_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.Column('maj_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['auteur_id'], ['blog.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='blog'
    )
    op.create_table('produits',
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prix', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('proprietaire_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.Column('maj_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proprietaire_id'], ['blog.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='blog'
    )
    op.create_table('commentaires',
    sa.Column('contenu', sa.Text(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('auteur_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cree_le', sa.DateTime(), nullable=True),
    sa.Column('maj_le', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['blog.articles.id'], ),
    sa.ForeignKeyConstraint(['auteur_id'], ['blog.users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='blog'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('commentaires', schema='blog')
    op.drop_table('produits', schema='blog')
    op.drop_table('articles', schema='blog')
    op.drop_table('users', schema='blog')
    # ### end Alembic commands ###
